export const ActionTypes = {
  ADD_POLYGON: 'ADD_POLYGON',
  UPDATE_POLYGON: 'UPDATE_POLYGON',
  DELETE_POLYGON: 'DELETE_POLYGON',
  ADD_MARKER: 'ADD_MARKER',
  UPDATE_MARKER: 'UPDATE_MARKER',
  DELETE_MARKER: 'DELETE_MARKER',
  SET_EDITING_MODE: 'SET_EDITING_MODE',
  SET_SELECTED_ITEM: 'SET_SELECTED_ITEM',
};
